# Generated by Django 5.1.1 on 2025-02-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the instruction', max_length=255, verbose_name='Instruction Name')),
                ('goal', models.CharField(help_text='Goal of the instruction', max_length=255, verbose_name='Goal')),
                ('description', models.TextField(help_text='Instruction description', verbose_name='Description')),
                ('date', models.DateField(help_text='Date for the instruction', verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the instruction was created', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': 'Instructions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InstructionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the instruction list', max_length=255, verbose_name='List Name')),
                ('description', models.TextField(help_text='Description of the list', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Attach an image for the list', null=True, upload_to='instruction_lists/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the list was created', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Instruction List',
                'verbose_name_plural': 'Instruction Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstructionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(help_text='Attach a video, image, or note', upload_to='instruction_attachments/', verbose_name='Attachment')),
                ('description', models.TextField(help_text='Attachment description', verbose_name='Description')),
                ('date', models.DateField(help_text='Date for the attachment', verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the attachment was added', verbose_name='Creation Date')),
                ('instruction', models.ForeignKey(help_text='Associated instruction', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='instructionsModule.instruction', verbose_name='Instruction')),
            ],
            options={
                'verbose_name': 'Instruction Attachment',
                'verbose_name_plural': 'Instruction Attachments',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_list',
            field=models.ForeignKey(help_text='Associated instruction list', on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='instructionsModule.instructionlist', verbose_name='Instruction List'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(help_text='Unique note number', max_length=50, unique=True, verbose_name='Note Number')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related entity', verbose_name='Object ID')),
                ('description', models.TextField(help_text='Note description', verbose_name='Description')),
                ('current_date', models.DateField(help_text='Current date', verbose_name='Current Date')),
                ('target_date', models.DateField(help_text='Target date for reminder', verbose_name='Target Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the note was created', verbose_name='Creation Date')),
                ('content_type', models.ForeignKey(help_text='Type of the related entity', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
