# Generated by Django 5.1.1 on 2025-02-09 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.CharField(max_length=50, unique=True, verbose_name='Bank Number')),
                ('name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('currency', models.CharField(max_length=10, verbose_name='Main Currency')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Report Date')),
                ('total_loans', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Loans')),
                ('paid_installments', models.PositiveIntegerField(verbose_name='Paid Installments')),
                ('unpaid_installments', models.PositiveIntegerField(verbose_name='Unpaid Installments')),
                ('overdue_loans', models.PositiveIntegerField(verbose_name='Overdue Loans')),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Interest')),
            ],
            options={
                'verbose_name': 'Loan Report',
                'verbose_name_plural': 'Loan Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=50, unique=True, verbose_name='Loan Number')),
                ('name', models.CharField(max_length=100, verbose_name='Loan Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Loan Amount')),
                ('receipt_date', models.DateField(verbose_name='Receipt Date')),
                ('duration', models.PositiveIntegerField(verbose_name='Loan Duration (months)')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate')),
                ('payment_method', models.CharField(choices=[('transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment Method')),
                ('installments_count', models.PositiveIntegerField(verbose_name='Number of Installments')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Installment Amount')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=20, verbose_name='Status')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='bankModule.bank', verbose_name='Related Bank')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='bankModule.loan', verbose_name='Loan')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['due_date'],
            },
        ),
    ]
