# Generated by Django 5.1.1 on 2025-02-09 18:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Wilaya Name')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('international_number', models.CharField(max_length=100, unique=True, verbose_name='International Land Number')),
                ('land_number', models.CharField(max_length=100, unique=True, verbose_name='Land Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (USD)')),
                ('land_type', models.CharField(choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=20, verbose_name='Land Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (sqm)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('plowed', 'Plowed'), ('rented', 'Rented'), ('cultivated', 'Cultivated')], default='available', max_length=20, verbose_name='Land Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase Date')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_lands', to=settings.AUTH_USER_MODEL, verbose_name='Current Owner')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previously_owned_lands', to=settings.AUTH_USER_MODEL, verbose_name='Previous Owner')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='landModule.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STATUS_CHANGE', 'Status Change')], max_length=20)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landModule.land')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
            },
        ),
        migrations.CreateModel(
            name='LandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='land_documents/', verbose_name='Document File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='landModule.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Land Document',
                'verbose_name_plural': 'Land Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='land_images/', verbose_name='Land Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Uploaded At')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landModule.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Land Image',
                'verbose_name_plural': 'Land Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LandTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price (USD)')),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Name')),
                ('buyer_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Phone')),
                ('buyer_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Buyer Email')),
                ('buyer_address', models.TextField(blank=True, null=True, verbose_name='Buyer Address')),
                ('purchase_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Purchase Date')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='landModule.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Land Transaction',
                'verbose_name_plural': 'Land Transactions',
            },
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['international_number'], name='landModule__interna_d3d9df_idx'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['land_number'], name='landModule__land_nu_5665bc_idx'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['wilaya'], name='landModule__wilaya__b1db5f_idx'),
        ),
    ]
