# Generated by Django 5.1.1 on 2025-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_number',
            field=models.CharField(default='ddd', max_length=100, verbose_name='Land Number'),
        ),
    ]
