# Generated by Django 5.1.1 on 2025-02-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the warehouse', max_length=255, verbose_name='Warehouse Name')),
                ('image', models.ImageField(blank=True, help_text='Attach an image for the warehouse', null=True, upload_to='warehouses/', verbose_name='Image')),
                ('description', models.TextField(help_text='Warehouse description', verbose_name='Description')),
                ('space', models.DecimalField(decimal_places=2, help_text='Total available space', max_digits=10, verbose_name='Space')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the warehouse was added', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuantityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Quantity threshold to trigger the reminder', max_digits=10, verbose_name='Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the reminder was set', verbose_name='Creation Date')),
                ('product', models.ForeignKey(help_text='Product for reminder', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_reminders', to='productModule.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(help_text='Warehouse for reminder', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_reminders', to='warehousModule.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Quantity Reminder',
                'verbose_name_plural': 'Quantity Reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuantityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('INC', 'Increase'), ('DEC', 'Decrease')], help_text='Target: Increase or Decrease quantity', max_length=3, verbose_name='Goal')),
                ('time_frame', models.CharField(choices=[('1D', 'One Day'), ('2D', 'Two Days'), ('3D', 'Three Days'), ('1W', 'One Week'), ('1M', 'One Month'), ('1Y', 'One Year')], help_text='Time period for adjustment', max_length=2, verbose_name='Time Frame')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity adjustment amount based on selected time', max_digits=10, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the control was set', verbose_name='Creation Date')),
                ('product', models.ForeignKey(help_text='Product for quantity control', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_controls', to='productModule.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(help_text='Warehouse for quantity control', on_delete=django.db.models.deletion.CASCADE, related_name='quantity_controls', to='warehousModule.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Quantity Control',
                'verbose_name_plural': 'Quantity Controls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity added to the warehouse', verbose_name='Quantity')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the added product', max_digits=10, verbose_name='Weight')),
                ('used_space', models.DecimalField(decimal_places=2, help_text='Space occupied in the warehouse', max_digits=10, verbose_name='Used Space')),
                ('date', models.DateField(help_text='Date when the product was added', verbose_name='Date')),
                ('product', models.ForeignKey(help_text='Product added to warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_entries', to='productModule.product', verbose_name='Product')),
                ('warehouse', models.ForeignKey(help_text='Associated warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='warehousModule.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Product Entry',
                'verbose_name_plural': 'Warehouse Product Entries',
                'ordering': ['-date'],
            },
        ),
    ]
