# Generated by Django 5.1.1 on 2025-02-09 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('department', models.CharField(choices=[('Animal', 'Animal'), ('Agricultural', 'Agricultural'), ('Other', 'Other')], max_length=20, verbose_name='Department')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('residence_location', models.CharField(max_length=255, verbose_name='Residence Location')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Salary')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/profile_pictures/', verbose_name='Profile Picture')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('work_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Work Latitude')),
                ('work_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Work Longitude')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, verbose_name='Marital Status')),
                ('annual_leave_allowance', models.PositiveIntegerField(default=30, verbose_name='Annual Leave Allowance')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('file', models.FileField(upload_to='employees/documents/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employeModule.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
            },
        ),
    ]
