# Generated by Django 5.1.1 on 2025-02-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeModule', '0002_department_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Certificate', 'Certificate'), ('Identity', 'Identity'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeModule.documentcategory', verbose_name='Category'),
        ),
    ]
