# Generated by Django 5.1.1 on 2025-02-09 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=255, verbose_name='Category Name')),
                ('description', models.TextField(help_text='Category description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the category was created', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the supplier list', max_length=255, verbose_name='List Name')),
                ('description', models.TextField(help_text='Description of the supplier list', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image for the supplier list', null=True, upload_to='supplier_lists/', verbose_name='List Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the list was created', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Supplier List',
                'verbose_name_plural': 'Supplier Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255, verbose_name='Product Name')),
                ('product_number', models.CharField(help_text='Unique product number', max_length=50, unique=True, verbose_name='Product Number')),
                ('description', models.TextField(help_text='Product description', verbose_name='Description')),
                ('benefit', models.TextField(help_text='Product benefit', verbose_name='Benefit')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Product weight', max_digits=10, null=True, verbose_name='Weight')),
                ('usage_duration', models.CharField(blank=True, help_text='Usage duration or effectiveness', max_length=100, null=True, verbose_name='Usage Duration')),
                ('product_age', models.CharField(blank=True, help_text='Age of the product', max_length=50, null=True, verbose_name='Product Age')),
                ('storage_instructions', models.TextField(blank=True, help_text='Instructions for storing the product', null=True, verbose_name='Storage Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the product was created', verbose_name='Creation Date')),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='animalModule.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image file', upload_to='product_images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True, verbose_name='Alt Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the image was added', verbose_name='Creation Date')),
                ('product', models.ForeignKey(help_text='Product for this image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animalModule.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the variant', max_length=255, verbose_name='Variant Name')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for the variant', max_digits=10, verbose_name='Additional Price')),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True, verbose_name='SKU')),
                ('product', models.ForeignKey(help_text='Product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='animalModule.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_number', models.CharField(help_text='Unique supplier number', max_length=50, unique=True, verbose_name='Supplier Number')),
                ('supplier_name', models.CharField(help_text='Name of the supplier', max_length=255, verbose_name='Supplier Name')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=255, verbose_name='Company Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product from this supplier', max_digits=10, verbose_name='Price')),
                ('phone', models.CharField(help_text='Supplier phone number', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(help_text='Supplier address', verbose_name='Address')),
                ('payment_method', models.CharField(help_text='Method of payment', max_length=100, verbose_name='Payment Method')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True, verbose_name='Notes')),
                ('product_image', models.ImageField(blank=True, help_text='Image of the product from the supplier', null=True, upload_to='supplier_products/', verbose_name='Product Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the supplier record was created', verbose_name='Creation Date')),
                ('product', models.ForeignKey(help_text='Related product', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='animalModule.product', verbose_name='Product')),
                ('supplier_list', models.ForeignKey(blank=True, help_text='Associated supplier list (e.g., Fuel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='animalModule.supplierlist', verbose_name='Supplier List')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='idx_product_number'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_number'], name='idx_supplier_number'),
        ),
    ]
