# Generated by Django 5.1.1 on 2025-02-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin Profile'), ('farm', 'Farm Profile'), ('farmmanager', 'Farm Manager'), ('user', 'User Profile')], help_text='User role for which this configuration applies.', max_length=20, unique=True)),
                ('primary_color', models.CharField(default='#3490dc', help_text='Primary color hex code (e.g., #3490dc).', max_length=7)),
                ('secondary_color', models.CharField(default='#ffed4a', help_text='Secondary color hex code (e.g., #ffed4a).', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color hex code (e.g., #ffffff).', max_length=7)),
                ('text_color', models.CharField(default='#1a202c', help_text='Text color hex code (e.g., #1a202c).', max_length=7)),
            ],
            options={
                'verbose_name': 'Theme Configuration',
                'verbose_name_plural': 'Theme Configurations',
            },
        ),
    ]
