# Generated by Django 5.1.1 on 2025-02-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.CharField(max_length=20, unique=True, verbose_name='Land Identifier')),
                ('name', models.CharField(max_length=255, verbose_name='Land Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('category', models.CharField(choices=[('Seed', 'بذور'), ('Fertilizer', 'سماد')], max_length=100, verbose_name='Category')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_id', models.CharField(max_length=20, unique=True, verbose_name='Crop Identifier')),
                ('status', models.CharField(choices=[('Planted', 'تم الزراعة'), ('Growing', 'ينمو'), ('Harvested', 'تم الحصاد')], max_length=50, verbose_name='Status')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Harvest Date')),
                ('usage', models.CharField(choices=[('SALE', 'Sale'), ('ANIMAL_FEED', 'Animal Feed')], max_length=50, verbose_name='Usage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='agricultureModule.land', verbose_name='Land')),
            ],
        ),
        migrations.CreateModel(
            name='LandCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('PLOWING', 'Plowing'), ('SMOOTHING', 'Smoothing'), ('PLANTING', 'Planting'), ('NON_ARABLE', 'Non-arable'), ('TREATMENT', 'Treatment'), ('UNUSED', 'Unused')], max_length=50, verbose_name='Condition')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity_used', models.FloatField(blank=True, null=True, verbose_name='Quantity Used')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='agricultureModule.land', verbose_name='Land')),
                ('product_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_conditions', to='agricultureModule.product', verbose_name='Product Used')),
            ],
        ),
        migrations.AddField(
            model_name='land',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='agricultureModule.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_land', models.IntegerField(verbose_name='Total Land')),
                ('total_crops', models.IntegerField(verbose_name='Total Crops')),
                ('total_yield', models.FloatField(verbose_name='Total Yield (tons)')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Report Date')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='agricultureModule.region', verbose_name='Region')),
            ],
        ),
    ]
